version: 1.13.{build}

pull_requests:
  do_not_increment_build_number: true

shallow_clone: true

environment:
  DODEPLOY: false
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
  ANDROID_HOME: C:\Program Files (x86)\Android\android-sdk
  ANDROID_NDK_VERSION: 21.0.6113669

install:
- echo "cmake.dir=C:\\Program Files\\CMake" > local.properties
- git clone --depth 1 https://github.com/labstreaminglayer/liblsl ../liblsl
- yes | "%ANDROID_HOME%\tools\bin\sdkmanager" --licenses > nul
- yes | "%ANDROID_HOME%\tools\bin\sdkmanager" "ndk;%ANDROID_NDK_VERSION%" > nul

build_script:
- gradlew assembleRelease

artifacts:
- path: 'build/outputs/aar/*.aar'
