name: Build # name of the workflow

on:
  push: # specifies events to trigger the workflow
    branches: [ main ] # branches that trigger the workflow
  jobs: # groups the jobs to be executed in this workflow

    build: # defines a job called build
      name: 🔨 Build # [optional] name of the job
      runs-on: ubuntu-latest # the job will be executed on ubuntu runner. Other include: Microsoft Windows & MacOS runners
      steps: # groups together all the steps that run in build job

        # Checks out code from the VCS to the runner
        - name: Checkout code # [optional] specifies the name of the step
          uses: actions/checkout@v2 # specifies which action and version to execute ie. checkout@v2

        # Setup JDK Version 11 in the runner
        - name: Set up JDK 11
          uses: actions/setup-java@v1
          with:
            java-version: '11'

        # Allow permissions to make gradle executable - This can removed by adding the gradlew file permission
        # directly into the repository using `git update-index --chmod=+x gradlew`
        # - name: Make gradle executable
        #  run: chmod +x ./gradlew

        # Execute gradle build command with stacktrace flag
        - name: Build with gradle
          run: ./gradlew build --stacktrace # Execute gradle script to build project

    generate-apk: # Job to generate debug apk
      name: ⚙️Generate APK
      needs: [ build ]
      runs-on: ubuntu-latest
      steps:

        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up JDK 11
          uses: actions/setup-java@v1
          with:
            java-version: '11'

        - name: Build debug apk
          run: ./gradlew assembleDebug --stacktrace

        - name: Upload debug apk
          uses: actions/upload-artifact@v1
          with:
            name: Android-CI-CD
            path: app/build/outputs/apk/debug/app-debug.apk